import { useState, type FormEvent } from "react";
import { AlertTriangle, ArrowRight, CheckCircle2 } from "lucide-react";
import { Button, Logo } from "@/components/app/basic";
import { ApiError, confirmPasswordReset } from "@/lib/api/authApi";

export function ResetPasswordPage() {
  const [resetToken, setResetToken] = useState(""); const [newPassword, setNewPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); setMessage(""); if (!resetToken.trim()) return setError("Enter the reset token from your instructions."); if (newPassword.length < 8) return setError("Password must be at least 8 characters."); if (newPassword !== confirmPassword) return setError("Passwords do not match."); setSubmitting(true); try { const result = await confirmPasswordReset({ resetToken, newPassword }); setMessage(result.message); } catch (err) { setError(err instanceof ApiError ? err.message : "Unable to reset your password. Please try again."); } finally { setSubmitting(false); } };
  return <div className="login-page"><div className="login-decoration"><div className="login-grid" /><div className="login-brand"><Logo /><div className="login-quote">A fresh password,<br /><em>a secure return.</em></div></div></div><main className="login-panel"><div className="login-panel-inner"><div className="login-mobile-brand"><Logo compact /></div><div className="login-eyebrow">CHOOSE A NEW PASSWORD</div><h1>Secure your<br /><span>workspace.</span></h1><form onSubmit={submit} className="login-form"><div><label className="field-label" htmlFor="reset-token">Reset token</label><input id="reset-token" className="eb-input" value={resetToken} onChange={(event) => setResetToken(event.target.value)} autoComplete="one-time-code" required /></div><div><label className="field-label" htmlFor="new-password">New password</label><input id="new-password" type="password" className="eb-input" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} autoComplete="new-password" minLength={8} maxLength={128} required /></div><div><label className="field-label" htmlFor="new-password-confirm">Confirm new password</label><input id="new-password-confirm" type="password" className="eb-input" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} autoComplete="new-password" minLength={8} maxLength={128} required /></div>{error && <div className="field-error"><AlertTriangle size={14} />{error}</div>}{message && <div className="form-success"><CheckCircle2 size={14} />{message}</div>}<Button type="submit" size="lg" className="w-full" disabled={submitting}>{submitting ? "Resetting password…" : <>Set new password <ArrowRight size={16} /></>}</Button></form><p className="login-legal"><a href="/login">Back to sign in</a></p></div></main></div>;
}
